services:
  mynginx:
    image: nginx:1.20-alpine
    container_name: mynginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork-front
    ports:
      - "8080:80"

  myphp:
    image: php:7.4-pdo
    container_name: myphp
    volumes:
      - ./php/:/srv/http/
    networks:
      - mynetwork-front
      - mynetwork-back

  mybdd:
    image: mariadb:10.5
    container_name: mybdd
    volumes:
      - mybdd:/var/lib/mysql
    networks:
      - mynetwork-back
    environment:
      MARIADB_ROOT_PASSWORD: roottoor

networks:
  mynetwork-front:
  mynetwork-back:

volumes:
  mybdd:
    external: true