version: "3.8"
services:
  mynginx:
    # Utilisation de variables declarées dans le fichier .env (chargé automatiquement par docker-compose)
    image: ${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}
    #container_name: mynginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork-front
    ports:
      - "8080:80"
    depends_on:
      - myphp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure
    env_file:
      - .env

  myphp:
    image: php:7.4-pdo
    #container_name: myphp
    volumes:
      - ./php/:/srv/http/
    networks:
      - mynetwork-front
      - mynetwork-back
    depends_on:
      - mybdd

  mybdd:
    image: mariadb:10.5
    #container_name: mybdd
    volumes:
      - mybdd:/var/lib/mysql
    networks:
      - mynetwork-back
    #environment:
    #  MARIADB_ROOT_PASSWORD: roottoor
    env_file:
      - .env

networks:
  mynetwork-front:
  mynetwork-back:

volumes:
  mybdd:
    # Utilisation d'une ressource externe -> deja presente sur le docker hote
    external: true