services:
  mynginx:
    image: nginx:1.20-alpine
    container_name: mynginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    ports:
      - "8080:80"

  myphp:
    image: php:7.4.24-fpm-pdo
    container_name: myphp
    volumes:
      - ./php/:/srv/http/
    networks:
      - mynetwork

  mybdd:
    image: mariadb:10.5
    container_name: mybdd
    volumes:
      - mybdd:/var/lib/docker
    networks:
      - mynetwork
    environment:
      MARIADB_ROOT_PASSWORD: roottoor

networks:
  mynetwork:

volumes:
  mybdd: